### ISSUE TITLE
Command prompt in raindrop

### ISSUE THREAD

**Issue by 0PandaDEV** [Haruno19/dotfiles#3]
How is your command prompt called you used in raindrop? Does not look like zsh to me

**Comment by Haruno19** [comment]
It is zsh! With Oh-my-zsh, and the theme is called aditya, you can find the file for it [here](https://github.com/Haruno19/dotfiles/blob/main/MacOS/Monochrome/aditya.zsh-theme):)

**Comment by 0PandaDEV** [comment]
Oh, that's even better because I like zsh so thanks
